(function () {
  const config = window.APP_SUPABASE || {};
  const client = config.url && config.anonKey && !config.anonKey.includes('PASTE_')
    ? window.supabase.createClient(config.url, config.anonKey) : null;
  const state = { mode: 'login', user: null, profile: null, entries: [], profiles: [], timer: null, driverFilter: 'all' };
  const $ = (id) => document.getElementById(id);
  const els = {
    authScreen: $('authScreen'), appScreen: $('appScreen'), authForm: $('authForm'), authTitle: $('authTitle'), authMessage: $('authMessage'), nameField: $('nameField'), nameInput: $('nameInput'), emailInput: $('emailInput'), passwordInput: $('passwordInput'), welcomeText: $('welcomeText'), logoutBtn: $('logoutBtn'), segments: document.querySelectorAll('.segment'), adminTools: $('adminTools'), driverFilter: $('driverFilter'), todayHours: $('todayHours'), weekHours: $('weekHours'), timerStatus: $('timerStatus'), elapsedTimer: $('elapsedTimer'), startTimerBtn: $('startTimerBtn'), stopTimerBtn: $('stopTimerBtn'), timerNotes: $('timerNotes'), timerTags: $('timerTags'), manualEntryForm: $('manualEntryForm'), manualStart: $('manualStart'), manualEnd: $('manualEnd'), manualNotes: $('manualNotes'), manualTags: $('manualTags'), clearManualBtn: $('clearManualBtn'), entriesList: $('entriesList'), dailyReport: $('dailyReport'), weeklyReport: $('weeklyReport'), exportCsvBtn: $('exportCsvBtn')
  };
  const setMessage = (text, kind = '') => { els.authMessage.textContent = text; els.authMessage.className = `message ${kind}`.trim(); };
  const tags = (value) => value.split(',').map((x) => x.trim()).filter(Boolean);
  const duration = (start, end) => Math.max(0, (new Date(end) - new Date(start)) / 60000);
  const fmtHours = (mins) => `${Math.floor(Math.max(0, Math.round(mins)) / 60)}h ${String(Math.max(0, Math.round(mins)) % 60).padStart(2, '0')}m`;
  const fmtTimer = (ms) => [Math.floor(ms / 3600000), Math.floor(ms / 60000) % 60, Math.floor(ms / 1000) % 60].map((x) => String(x).padStart(2, '0')).join(':');
  const fmtDate = (value) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value));
  const dayKey = (value) => new Date(value).toISOString().slice(0, 10);
  function weekStart(value) { const d = new Date(value); const diff = d.getDay() === 0 ? -6 : 1 - d.getDay(); d.setHours(0, 0, 0, 0); d.setDate(d.getDate() + diff); return d; }
  function setMode(mode) { state.mode = mode; els.segments.forEach((b) => b.classList.toggle('active', b.dataset.mode === mode)); els.authTitle.textContent = mode === 'signup' ? 'Create Account' : 'Driver Login'; els.nameField.classList.toggle('hidden', mode !== 'signup'); els.nameInput.required = mode === 'signup'; els.authForm.querySelector('button[type=submit]').textContent = mode === 'signup' ? 'Create account' : 'Continue'; }
  async function getUser() { const { data, error } = await client.auth.getUser(); return error ? null : data.user; }
  async function signUp() { const name = els.nameInput.value.trim(); if (!name) return { error: { message: 'Enter your full name.' } }; const { data, error } = await client.auth.signUp({ email: els.emailInput.value.trim(), password: els.passwordInput.value, options: { data: { full_name: name } } }); return { data, error }; }
  async function loadProfile(user) { const { data, error } = await client.from('profiles').select('id,email,full_name,is_admin').eq('id', user.id).maybeSingle(); if (error) throw error; state.profile = data || { id: user.id, email: user.email, full_name: user.user_metadata?.full_name || user.email, is_admin: false }; state.user = user; }
  async function loadProfiles() { if (!state.profile?.is_admin) return; const { data, error } = await client.from('profiles').select('id,email,full_name,is_admin').order('full_name'); if (error) throw error; state.profiles = data || []; els.driverFilter.innerHTML = '<option value="all">All drivers</option>' + state.profiles.filter((p) => !p.is_admin).map((p) => `<option value="${p.id}">${p.full_name || p.email}</option>`).join(''); }
  async function loadEntries() { let query = client.from('time_entries').select('*').order('start_time', { ascending: false }); if (state.profile?.is_admin && state.driverFilter !== 'all') query = query.eq('user_id', state.driverFilter); else if (!state.profile?.is_admin) query = query.eq('user_id', state.user.id); const { data, error } = await query; if (error) throw error; const lookup = Object.fromEntries(state.profiles.map((p) => [p.id, p])); state.entries = (data || []).map((e) => ({ id: e.id, userId: e.user_id, userName: lookup[e.user_id]?.full_name || lookup[e.user_id]?.email || (e.user_id === state.user.id ? state.profile.full_name : 'Driver'), start: e.start_time, end: e.end_time || e.start_time, durationMinutes: e.end_time ? duration(e.start_time, e.end_time) : 0, notes: e.notes || '', tags: e.tags || [] })); }
  function visibleEntries() { return state.entries; }
  function render() { const entries = visibleEntries(); els.entriesList.innerHTML = entries.length ? entries.map((e) => `<article class="entry-item"><div class="entry-top"><div><strong>${state.profile?.is_admin ? e.userName : ''}</strong><div class="entry-time">${fmtDate(e.start)} → ${fmtDate(e.end)}</div></div><span class="duration-badge">${fmtHours(e.durationMinutes)}</span></div><div class="entry-notes">${e.notes || 'No notes added.'}</div><div class="tags">${e.tags.length ? e.tags.map((t) => `<span class="tag">${t}</span>`).join('') : '<span class="tag">untagged</span>'}</div></article>`).join('') : '<div class="empty-state">No time entries yet.</div>'; const daily = {}, weekly = {}; entries.forEach((e) => { daily[dayKey(e.start)] = (daily[dayKey(e.start)] || 0) + e.durationMinutes; const w = weekStart(e.start).toISOString().slice(0, 10); weekly[w] = (weekly[w] || 0) + e.durationMinutes; }); const rows = (obj, limit) => Object.entries(obj).sort((a, b) => b[0].localeCompare(a[0])).slice(0, limit).map(([k, v]) => `<div class="report-row"><span>${k}</span><strong>${fmtHours(v)}</strong></div>`).join(''); els.dailyReport.innerHTML = rows(daily, 7) || '<div class="empty-state">No daily data.</div>'; els.weeklyReport.innerHTML = rows(weekly, 8) || '<div class="empty-state">No weekly data.</div>'; const now = new Date(), today = new Date(now.getFullYear(), now.getMonth(), now.getDate()), ws = weekStart(now); els.todayHours.textContent = fmtHours(entries.filter((e) => new Date(e.end) >= today).reduce((s, e) => s + e.durationMinutes, 0)); els.weekHours.textContent = fmtHours(entries.filter((e) => new Date(e.end) >= ws).reduce((s, e) => s + e.durationMinutes, 0)); updateTimer(); }
  function updateTimer() { if (state.timer) { els.elapsedTimer.textContent = fmtTimer(Date.now() - new Date(state.timer.start)); els.timerStatus.textContent = 'Running'; els.startTimerBtn.disabled = true; els.stopTimerBtn.disabled = false; } else { els.elapsedTimer.textContent = '00:00:00'; els.timerStatus.textContent = 'Stopped'; els.startTimerBtn.disabled = false; els.stopTimerBtn.disabled = true; } }
  async function showApp() { els.authScreen.classList.add('hidden'); els.appScreen.classList.remove('hidden'); els.logoutBtn.classList.remove('hidden'); els.welcomeText.textContent = `Welcome, ${state.profile.full_name || state.profile.email}`; els.welcomeText.classList.remove('hidden'); els.adminTools.classList.toggle('hidden', !state.profile.is_admin); if (state.profile.is_admin) await loadProfiles(); await loadEntries(); render(); }
  async function authSubmit(event) { event.preventDefault(); if (!client) return setMessage('Add your complete Supabase anon/public key in index.html.', 'error'); const email = els.emailInput.value.trim(); if (state.mode === 'signup') { const { error } = await signUp(); if (error) return setMessage(error.message, 'error'); setMessage('Account created. Check your email, then log in.', 'success'); setMode('login'); return; } const { error } = await client.auth.signInWithPassword({ email, password: els.passwordInput.value }); if (error) return setMessage(error.message, 'error'); const user = await getUser(); await loadProfile(user); await showApp(); }
  async function startTimer() { if (state.timer) return setMessage('A timer is already running.', 'error'); state.timer = { start: new Date().toISOString(), notes: els.timerNotes.value.trim(), tags: tags(els.timerTags.value) }; updateTimer(); setMessage('Shift timer started.', 'success'); }
  async function stopTimer() { if (!state.timer) return; const user = await getUser(); const end = new Date().toISOString(); const { error } = await client.from('time_entries').insert({ user_id: user.id, start_time: state.timer.start, end_time: end, notes: state.timer.notes || 'Shift logged', tags: state.timer.tags }); if (error) return setMessage(error.message, 'error'); state.timer = null; els.timerNotes.value = ''; els.timerTags.value = ''; await loadEntries(); render(); setMessage('Shift saved.', 'success'); }
  async function manualSubmit(event) { event.preventDefault(); const start = new Date(els.manualStart.value), end = new Date(els.manualEnd.value); if (!els.manualStart.value || !els.manualEnd.value || end <= start) return setMessage('Choose valid start and end times.', 'error'); const user = await getUser(); const { error } = await client.from('time_entries').insert({ user_id: user.id, start_time: start.toISOString(), end_time: end.toISOString(), notes: els.manualNotes.value.trim() || 'Manual entry', tags: tags(els.manualTags.value) }); if (error) return setMessage(error.message, 'error'); els.manualEntryForm.reset(); await loadEntries(); render(); setMessage('Manual entry saved.', 'success'); }
  function exportCsv() { const entries = visibleEntries(); if (!entries.length) return setMessage('There are no entries to export.', 'error'); const rows = [['Driver', 'Start', 'End', 'Duration (minutes)', 'Notes', 'Tags'], ...entries.map((e) => [e.userName, e.start, e.end, Math.round(e.durationMinutes), e.notes, e.tags.join('; ')] )]; const csv = rows.map((r) => r.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = `driver_time_log_${new Date().toISOString().slice(0, 10)}.csv`; link.click(); }
  async function init() { if (!client) { setMessage('Add your complete Supabase anon/public key in index.html.', 'error'); return; } els.segments.forEach((b) => b.addEventListener('click', () => setMode(b.dataset.mode))); els.authForm.addEventListener('submit', authSubmit); els.logoutBtn.addEventListener('click', async () => { await client.auth.signOut(); location.reload(); }); els.startTimerBtn.addEventListener('click', startTimer); els.stopTimerBtn.addEventListener('click', stopTimer); els.manualEntryForm.addEventListener('submit', manualSubmit); els.clearManualBtn.addEventListener('click', () => els.manualEntryForm.reset()); els.exportCsvBtn.addEventListener('click', exportCsv); els.driverFilter.addEventListener('change', async () => { state.driverFilter = els.driverFilter.value; await loadEntries(); render(); }); const { data: { session } } = await client.auth.getSession(); if (session?.user) { await loadProfile(session.user); await showApp(); } setMode('login'); setInterval(updateTimer, 1000); }
  init();
})();
